### ISSUE TITLE
Show how to run docker composed detached

### ISSUE THREAD

**Issue by rstento** [lightbend/kalix-javascript-sdk#160]
@rstento commented on [Fri Aug 20 2021](https://github.com/lightbend/akkaserverless-java-sdk/issues/229)

From @mckeeh3: In the Run Service Locally / Starting the service section, provide an example and short details for running docker-compose using detached mode. See docker-compose up --help for details.

macOS and Windows

docker-compose up -d
Linux

docker-compose -f docker-compose.yml -f docker-compose.linux.yml up -d

**Comment by octonato** [comment]
This is less relevant because now docker-compose is run by the kalix plugin.
