### ISSUE TITLE
TypeScript support for codegen and kickstart

### ISSUE THREAD

**Issue by pvlugter** [lightbend/kalix-javascript-sdk#163]
Support generating TypeScript kickstart projects and code. Probably a switch on the existing scripts to generate TS instead of JS.

The TypeScript code generation could also follow the approach being developed for the Java SDK, where an interface is generated to be implemented, and hooking up with command/event handlers is automatic.

**Comment by janory** [comment]
Don't forget to remove [this](https://github.com/lightbend/akkaserverless-javascript-sdk/pull/166#discussion_r702886921) "cleanup hack" in the context of this issue.

**Comment by janory** [comment]
@pvlugter I will start working this now.

**Comment by janory** [comment]
Some work was already done related to this task.
It can be found [here](https://github.com/lightbend/akkaserverless-javascript-sdk/tree/163-typeScript_support_for_codegen/codegen/js-gen/src/main/scala/com/lightbend/akkasls/codegen/ts).
