### ISSUE TITLE
Support for BytesValue/StringValue wrapper types in eventing-in

### ISSUE THREAD

**Issue by raboof** [lightbend/kalix-javascript-sdk#262]
Events coming in with no content type or text content types get turned into BytesValue/StringValue wrapper types, but these likely aren't supported by the deserialization in this SDK yet

**Comment by johanandren** [comment]
When fixing https://github.com/lightbend/kalix-proxy/pull/1374 it seemed like this already works as expected.

**Comment by raboof** [comment]
Ace!
