### ISSUE TITLE
Remove behaviour approach from Event Sourced Entity?

### ISSUE THREAD

**Issue by pvlugter** [lightbend/kalix-javascript-sdk#334]
Event Sourced Entity is still using a behaviour approach, where the current state is passed to a callback with a behaviour returned (command handlers and event handlers).

https://github.com/lightbend/kalix-javascript-sdk/blob/50563b8cf07c6c3078e65dab16886cc7a2ae2cd2/sdk/src/event-sourced-entity.ts#L73-L102

Should we remove this and just have fixed command and event handlers?

**Comment by johanandren** [comment]
Sounds like a reasonable simplification to me (but breaking I guess?)

**Comment by pvlugter** [comment]
Yes, would be a breaking change. The other components don't use this approach, so looks like a leftover. Could have it go through a deprecation cycle first. Add command handlers and event handlers separately, which will be used for a default behaviour. Deprecate behaviour based on state. Remove much later.

**Comment by ennru** [comment]
See even https://github.com/lightbend/kalix-jvm-sdk/issues/980

**Comment by pvlugter** [comment]
Yes, saw the discussion on (re)introducing behaviours. So maybe this should instead be adding it to value entities as well, and making behaviours an optional approach in both. Extending with an FSM abstraction on top of handlers is probably possible already.

**Comment by octonato** [comment]
I'm curious to see how we could make an FSM abstraction on top of it. I don't see that as possible when using the codegen. 

If we encode everything by hand, yes that's possible, but challenging with the codegen. Because we don't have inheritance in protobuf, how can we switch behavior based on state? Unless event handlers to return `any` and at runtime we check if there is a behavior for it or not. 

I find it a degradation with respect to the hosting language. Certainly not a problem for Javascript, but kind of annoying for users picking Typescript but having to deal with `any`.

**Comment by pvlugter** [comment]
TypeScript has other features, such as union types.

So the codegen will generate a union type for events already. Such as in the event-sourced shopping cart:

```ts
export declare namespace ShoppingCartService {
  type State = domain.Cart;

  type Events =
    | domain.ItemAdded
    | domain.ItemRemoved;

  ...
}
```

You can also create and pass that as a type parameter to an entity yourself.

The command context is typed with the `Events` so that the `emit` effect only accepts those types.

And the entity uses a [distributive conditional](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types) to type the event handlers:

https://github.com/lightbend/kalix-javascript-sdk/blob/ad4e91c8fcc7304a0c0f18474056314e2bb86d37/sdk/src/event-sourced-entity.ts#L106-L111

So that the union of events for the shopping cart becomes a union of the possible event handlers. Effectively this for the shopping cart:

```ts
type EventHandler =
  | (event: domain.ItemAdded, state: domain.Cart) => domain.Cart
  | (event: domain.ItemRemoved, state: domain.Cart) => domain.Cart
```

You can have this typed support with or without the codegen or protobuf features, by passing a union of event types.

Can be similar for state types in an FSM abstraction.

**Comment by pvlugter** [comment]
I think let's leave it as is — event sourced entities with behaviours, value entities without. May be useful to have an example of changing behaviour and creating an event sourced state machine in the docs at some point.
