### ISSUE TITLE
Release Kalix JavaScript SDK 1.0.0-M10

### ISSUE THREAD

**Issue by johanandren** [lightbend/kalix-javascript-sdk#367]
### Prepare

- [x] Make sure all important PRs have been merged
- [x] Check that the [latest build](https://app.circleci.com/pipelines/github/lightbend/kalix-javascript-sdk) successfully finished
- [x] Make sure a version of the proxy that supports the protocol version the SDK expects has been deployed to production

You can see the proxy version on prod [on grafana](https://lightbendcloud.grafana.net/d/ebzw4ARnz/prod-akka-serverless-operations-dashboard?orgId=1) or using [various other methods](https://github.com/lightbend/kalix/wiki/Versioning-and-how-to-determine-what-version-is-running).

### Cutting the release

- [x] Edit the [draft release notes](https://github.com/lightbend/kalix-javascript-sdk/releases) and create the appropriate tag
    - CircleCI will automatically publish the [@kalix-io/kalix-javascript-sdk package](https://www.npmjs.com/package/@kalix-io/kalix-javascript-sdk) to the npm registry based on the tag
    - CI will update the docs/kalix-current branch

### Check availability

- [x] Check that [`docs/kalix-current`](https://github.com/lightbend/kalix-javascript-sdk/commits/docs/kalix-current) has been updated
- [x] Check the release in the [npm registry](https://www.npmjs.com/package/@kalix-io/kalix-javascript-sdk)

### Fix and publish docs

- [ ] Update the [latest version in the main docs](https://github.com/lightbend/kalix-docs/blob/main/docs/modules/ROOT/partials/include.adoc#L21)
- [ ] If relevant, update the [supported version in the main docs](https://github.com/lightbend/kalix-docs/blob/main/docs/modules/ROOT/partials/include.adoc#L20) (affects [Supported Versions](https://docs.kalix.io/setting-up/index.html#_supported_languages))
- [x] Add an item to the [Release Notes](https://github.com/lightbend/kalix-docs/blob/main/docs/modules/release-notes/pages/index.adoc) in the documentation
- [ ] Release the Kalix documentation to get the SDK docs updates published

### Update to the latest version

- [ ] Run `samples/bin/update.sh` to update the samples to the latest released versions.

### Check docs update

- [ ] After quite a while TechHub shows [updated docs](https://docs.kalix.io/index.html) (see the timestamp on the bottom of the page)

### Announcements

- [ ] Announce in [the forum](https://discuss.kalix.io)
    - tag with Kalix, releases and announcement
- [ ] Inform Lightbend marketing and engineering if it's a noteworthy release
- [ ] Close this issue

**Comment by johanandren** [comment]
Hmm, publishing failed when compiling the testkit https://app.circleci.com/pipelines/github/lightbend/kalix-javascript-sdk/1169/workflows/ca7d7a1e-fefd-44d7-b1c3-33f0aa6b2c9c/jobs/7418

**Comment by pvlugter** [comment]
Published the rest of M10 manually.

The testkit currently has an SDK `^1.0.0-M7` peer and dev dependency — which was the minimum version it was compatible with before. Seems that npm publishing is not that well suited to multiple packages, and is also set up for committing changes as part of a release. And I'm not sure whether the just published SDK can be referenced and downloaded immediately. Will see if there's some combination that will be better going forward for when the SDK and testkit need changes together.

**Comment by pvlugter** [comment]
> However, when I got to the testkit, it promptly wants to use M7 for some reason I don't get, even with an updated package.json `npm install` will pull in M7 into the `package-lock.json`.

I think this could be because npm uses the semantic versioning spec exactly. The prerelease version needs the numeric part to be separate. So `-m.7` would work. Or `beta.7` as we used earlier (for this reason I think).
