### ISSUE TITLE
Publish docs not being published and failing silently

### ISSUE THREAD

**Issue by efgpinto** [lightbend/kalix-javascript-sdk#473]
JS SDK docs are not being published correctly and fail silently. See [here](https://app.circleci.com/pipelines/github/lightbend/kalix-javascript-sdk/1587/workflows/98c736cb-11b6-4e38-8a4b-ede056619ccc/jobs/9614?invite=true#step-103-106)

This issue is about making sure the docs get publish and also that it does not fail silently again.

**Comment by ennru** [comment]
Should be fixed with a fresh key in
- #493
