### ISSUE TITLE
Make testkit part of SDK instead of generated from codegen

### ISSUE THREAD

**Issue by octonato** [lightbend/kalix-javascript-sdk#80]
The javascript codegen generates a testkit for value entities and event sourced entities that are very similar to Akka's EventSourcedBehaviorTestkit. 

Instead of generating this over and over, we should make it part of the SDK itself.

**Comment by pvlugter** [comment]
Could also introduce a separate testkit package, rather than including in the SDK, so that it can be a dev dependency only.

**Comment by pvlugter** [comment]
Testkit should be the typed version of the mock entities, for TypeScript support.
